// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type VerificationSession struct {
	ID             uuid.UUID
	UserID         string
	SessionID      string
	Status         string
	DiditSessionID sql.NullString
	UserEmail      string
	UserFirstName  sql.NullString
	UserLastName   sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
	Metadata       pqtype.NullRawMessage
}

type WebhookEvent struct {
	ID        uuid.UUID
	EventType string
	SessionID string
	Payload   json.RawMessage
	Processed sql.NullBool
	CreatedAt time.Time
}
